<a href="https://colab.research.google.com/github/Akkume/Akkume/blob/main/MLIO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print("akshay")

akshay


its awesomeee..naaah..its tuesday 

In [5]:
import numpy as np

In [10]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print(A[0][1])

[[1 2 3]
 [4 5 6]]
2


In [9]:
print(A[0][1])

2


In [11]:
print(A[0,1])

2


In [12]:
print(A[0:2,0:1])

[[1]
 [4]]
